version: '3.8'

services:
  evolution_postgres:
    image: postgres:15
    container_name: evolution_postgres
    restart: always
    environment:
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: SecretPassword123!
      POSTGRES_DB: evolution_db
    volumes:
      - evolution_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  evolution_redis:
    image: redis:alpine
    container_name: evolution_redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - evolution_redisdata:/data
    ports:
      - "6379:6379"

  evolution_api:
    image: evoapicloud/evolution-api:v2.3.7
    container_name: evolution_api
    restart: always
    depends_on:
      - evolution_postgres
      - evolution_redis
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=https://api.seusite.com
      - AUTHENTICATION_API_KEY=SuaChaveGlobal123@
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evolution:SecretPassword123!@evolution_postgres:5432/evolution_db?schema=public
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_api
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://evolution_redis:6379/1
      - CACHE_REDIS_PREFIX_KEY=evo
      - REDIS_URI=redis://evolution_redis:6379/1
      - REDIS_PREFIX_KEY=evo
      - WEBSOCKET_ENABLED=true
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

volumes:
  evolution_pgdata:
  evolution_redisdata:
  evolution_instances:
  evolution_store:
